import { Template } from "@/types/template";

/**
 * Get default templates for the application
 */
export function getDefaultTemplates(): Template[] {
  const now = new Date();

  return [
    {
      id: "template-general",
      name: "General Business Proposal",
      description: "A versatile template for any business proposal",
      category: "general",
      sections: [
        {
          id: "section-1",
          type: "header",
          title: "Cover Page",
          defaultContent: "Project Title\n\nPrepared for: [Client Name]\nPrepared by: [Your Name/Company]\nDate: [Date]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "about",
          title: "About Us",
          defaultContent: "Brief introduction about your company and expertise.",
          order: 1,
          isRequired: false,
        },
        {
          id: "section-3",
          type: "services",
          title: "Services",
          defaultContent: "Detailed description of the services you will provide.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "pricing",
          title: "Pricing",
          defaultContent: "Breakdown of costs and payment terms.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "timeline",
          title: "Timeline",
          defaultContent: "Project timeline and milestones.",
          order: 4,
          isRequired: false,
        },
      ],
      isPremium: false,
      createdAt: now,
    },
    {
      id: "template-consulting",
      name: "Consulting Services",
      description: "Perfect for consulting professionals",
      category: "consulting",
      sections: [
        {
          id: "section-1",
          type: "header",
          title: "Executive Summary",
          defaultContent: "Consulting Proposal\n\n[Client Name]\n[Date]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "about",
          title: "Our Approach",
          defaultContent: "Our consulting methodology and approach to solving your challenges.",
          order: 1,
          isRequired: true,
        },
        {
          id: "section-3",
          type: "services",
          title: "Consulting Services",
          defaultContent: "Detailed breakdown of consulting services to be provided.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "pricing",
          title: "Investment",
          defaultContent: "Consulting fees and payment structure.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "timeline",
          title: "Project Timeline",
          defaultContent: "Phases and deliverables timeline.",
          order: 4,
          isRequired: true,
        },
      ],
      isPremium: false,
      createdAt: now,
    },
    {
      id: "template-design",
      name: "Design Services",
      description: "Tailored for design agencies and freelancers",
      category: "design",
      sections: [
        {
          id: "section-1",
          type: "hero",
          title: "Design Proposal",
          defaultContent: "Creative design solutions for [Client Name]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "services",
          title: "Design Services",
          defaultContent: "Logo design, branding, web design, print materials, etc.",
          order: 1,
          isRequired: true,
        },
        {
          id: "section-3",
          type: "pricing",
          title: "Pricing",
          defaultContent: "Package options and pricing tiers.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "timeline",
          title: "Project Timeline",
          defaultContent: "Design phases and delivery dates.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "testimonials",
          title: "Portfolio & Testimonials",
          defaultContent: "Previous work examples and client testimonials.",
          order: 4,
          isRequired: false,
        },
      ],
      isPremium: true,
      createdAt: now,
    },
    {
      id: "template-development",
      name: "Development Proposal",
      description: "Ideal for software development projects",
      category: "development",
      sections: [
        {
          id: "section-1",
          type: "header",
          title: "Project Overview",
          defaultContent: "Software Development Proposal\n\n[Project Name]\n[Client Name]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "services",
          title: "Technical Scope",
          defaultContent: "Technologies, features, and deliverables.",
          order: 1,
          isRequired: true,
        },
        {
          id: "section-3",
          type: "timeline",
          title: "Development Phases",
          defaultContent: "Sprint planning, milestones, and delivery schedule.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "pricing",
          title: "Budget",
          defaultContent: "Development costs and payment schedule.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "about",
          title: "Team & Experience",
          defaultContent: "Development team and relevant experience.",
          order: 4,
          isRequired: false,
        },
      ],
      isPremium: false,
      createdAt: now,
    },
    {
      id: "template-marketing",
      name: "Marketing Campaign",
      description: "Comprehensive marketing proposal template",
      category: "marketing",
      sections: [
        {
          id: "section-1",
          type: "hero",
          title: "Marketing Strategy",
          defaultContent: "Marketing Campaign Proposal for [Client Name]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "services",
          title: "Marketing Services",
          defaultContent: "SEO, social media, content marketing, PPC, etc.",
          order: 1,
          isRequired: true,
        },
        {
          id: "section-3",
          type: "pricing",
          title: "Investment",
          defaultContent: "Marketing budget and ROI projections.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "timeline",
          title: "Campaign Timeline",
          defaultContent: "Marketing activities and milestones.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "testimonials",
          title: "Case Studies",
          defaultContent: "Previous marketing campaign results.",
          order: 4,
          isRequired: false,
        },
      ],
      isPremium: true,
      createdAt: now,
    },
    {
      id: "template-client",
      name: "Client Proposal",
      description: "Professional proposal template for client presentations",
      category: "client",
      sections: [
        {
          id: "section-1",
          type: "header",
          title: "Proposal",
          defaultContent: "Proposal for [Client Name]\n\n[Your Company Name]\n[Date]",
          order: 0,
          isRequired: true,
        },
        {
          id: "section-2",
          type: "about",
          title: "Understanding Your Needs",
          defaultContent: "Summary of client requirements and objectives.",
          order: 1,
          isRequired: true,
        },
        {
          id: "section-3",
          type: "services",
          title: "Proposed Solution",
          defaultContent: "Detailed solution and approach to meet client needs.",
          order: 2,
          isRequired: true,
        },
        {
          id: "section-4",
          type: "pricing",
          title: "Investment & Terms",
          defaultContent: "Pricing, payment terms, and contract details.",
          order: 3,
          isRequired: true,
        },
        {
          id: "section-5",
          type: "timeline",
          title: "Project Timeline",
          defaultContent: "Key milestones and delivery schedule.",
          order: 4,
          isRequired: true,
        },
        {
          id: "section-6",
          type: "contact",
          title: "Next Steps",
          defaultContent: "How to proceed and contact information.",
          order: 5,
          isRequired: false,
        },
      ],
      isPremium: false,
      createdAt: now,
    },
  ];
}

